"use client";
import { useEffect,useState } from 'react';
import { Button } from '@/components/ui/button';
import { historySummary,type SharedObservation } from '@/lib/community-history';
import { evidenceTime } from '@/lib/station-evidence';
type History={personal:{id:string;status:string;reportedAt:number}[];community:SharedObservation[];asOf:number};
const labels:Record<string,string>={charged:'Successfully charged',working:'Reported working',busy:'Reported busy',broken:'Reported broken',problem:'Charging problem'};
export function ChargerHistory({stationId,version,onPrivateCleared}:{stationId:string;version:number|undefined;onPrivateCleared:()=>void}){
 const [data,setData]=useState<History|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[notice,setNotice]=useState('');
 const [status,setStatus]=useState('charged'),[consent,setConsent]=useState(false);
 useEffect(()=>{const controller=new AbortController();
  void Promise.resolve().then(()=>{if(controller.signal.aborted)return;setLoading(true);setError('');return fetch(`/api/community?stationId=${encodeURIComponent(stationId)}`,{signal:controller.signal});}).then(async r=>{if(!r)return;const body=await r.json() as History&{error?:string};if(!r.ok)throw new Error(body.error||'History could not be loaded.');if(!controller.signal.aborted)setData(body);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();
 },[stationId,version,revision]);
 async function act(method:string,path:string,body?:unknown,clearing=false){setBusy(true);setError('');setNotice('');try{
  const response=await fetch(path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'The change could not be saved.');
  setConsent(false);setRevision(n=>n+1);if(clearing)onPrivateCleared();setNotice(clearing?'Private history and current report cleared.':method==='POST'?'Your observation is shared.':method==='PATCH'?'Observation hidden after your flag.':'Your observation was withdrawn.');
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const summary=data?historySummary(data.community):null;
 return <section className="charger-history" aria-label="Charger history and community confirmations"><p className="eyebrow">Driver observations</p><h2>Charger history</h2><p>Reports describe a past observation. They do not confirm a working charger or a free port now.</p>
 <Button type="button" variant="outline" disabled={loading||busy} onClick={()=>{setLoading(true);setRevision(n=>n+1);}}>Refresh history</Button>
 {loading&&<p role="status">Loading observations…</p>}{error&&<p className="error-text" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {data&&!loading&&<><details><summary>Your private history ({data.personal.length})</summary><p>Only you can see these records. Up to 100 shown; the latest 500 are retained across your chargers. Earlier overwritten reports cannot be recovered.</p>{!data.personal.length&&<p>No private observations recorded here.</p>}<ul>{data.personal.map(r=><li key={r.id}><strong>{labels[r.status]||'Observation'}</strong><time dateTime={new Date(r.reportedAt).toISOString()}>{evidenceTime(r.reportedAt)}</time></li>)}</ul>{data.personal.length>0&&<Button type="button" variant="outline" disabled={busy} onClick={()=>act('DELETE',`/api/community?scope=private&stationId=${encodeURIComponent(stationId)}`,undefined,true)}>Delete my private history & current report</Button>}</details>
 <h3>Community confirmations</h3><p>Last 30 days, up to 100 entries. One entry per driver, station and UTC day. Counts describe these shared reports, not charger reliability or busy-hour predictions.</p><div className="history-counts"><span><strong>{summary!.charged}</strong> successful charges</span><span><strong>{summary!.busy}</strong> busy reports</span><span><strong>{summary!.problem}</strong> problem reports</span></div>{!summary!.total&&<p>No shared observations in this list. Charger operation remains unconfirmed.</p>}
 <ul>{data.community.map(r=><li key={r.id}><strong>{labels[r.status]}</strong><time dateTime={new Date(r.reportedAt).toISOString()}>{evidenceTime(r.reportedAt)}</time><small>{r.mine?'Your observation':'Community member'} · {r.visibility==='shared'?'Self-reported, not operator-verified':r.visibility==='hidden'?'Hidden after a flag':'Withdrawn'}</small>{r.mine&&r.visibility!=='withdrawn'?<Button variant="outline" disabled={busy} onClick={()=>act('DELETE',`/api/community?id=${encodeURIComponent(r.id)}`)}>Withdraw my observation</Button>:!r.mine&&r.visibility==='shared'?<Button variant="outline" disabled={busy} onClick={()=>act('PATCH','/api/community',{id:r.id})}>Flag inaccurate observation</Button>:null}</li>)}</ul><p className="muted-small">Flags hide an observation from other viewers. This is a reporting safeguard, not an independent verification or human review. Updated {evidenceTime(data.asOf)}.</p>
 </>}
 <form onSubmit={e=>{e.preventDefault();if(consent&&!busy)void act('POST','/api/community',{stationId,status,consent:true,observedNow:true});}}><h3>Share your own observation</h3><label>What happened?<select value={status} onChange={e=>{setStatus(e.target.value);setConsent(false);}}><option value="charged">Successfully charged here</option><option value="busy">Charger was busy</option><option value="problem">I had a charging problem</option></select></label><label className="history-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I personally observed this here now and agree to share the observation and timestamp with people who can access VoltRoute.</label><p className="muted-small">Your name, email and private notes are not shown. Site access settings still apply. Sharing again today updates your daily entry. You can withdraw it later.</p><Button type="submit" disabled={!consent||busy}>{busy?'Saving…':'Share observation'}</Button></form>
 </section>;
}
