"use client";
import { useEffect,useState } from 'react';
import { Button } from '@/components/ui/button';
import type { Station } from '@/lib/ev';
import { estimateSession,sessionClock,type SessionEstimate } from '@/lib/charge-session';
const empty={capacity:'',from:'',target:'80',averageKW:'',idleRate:'',graceMinutes:''};
type Active={estimate:SessionEstimate;stationName:string;stationId:string;vehicleName:string;finishedAt:number|null};
export function ChargeSessionAssistant({station,vehicleName,enteredRate}:{station:Station|null;vehicleName:string;enteredRate:string}){
 const [fields,setFields]=useState(empty),[started,setStarted]=useState(false),[active,setActive]=useState<Active|null>(null),[now,setNow]=useState<number|null>(null),[error,setError]=useState('');
 useEffect(()=>{if(!active){setFields(empty);setStarted(false);setError('');}},[station?.id,vehicleName,active]);
 useEffect(()=>{if(!active)return;const tick=()=>setNow(Date.now());tick();const timer=window.setInterval(tick,1000);window.addEventListener('focus',tick);document.addEventListener('visibilitychange',tick);return()=>{window.clearInterval(timer);window.removeEventListener('focus',tick);document.removeEventListener('visibilitychange',tick);};},[active]);
 const clock=active&&now!==null?sessionClock(active.estimate,active.finishedAt,now):null;
 if(!station&&!active)return null;
 const numeric=(key:keyof typeof fields)=>fields[key].trim()===''?NaN:Number(fields[key]);
 function start(){if(!station||!started)return;const timestamp=Date.now();const estimate=estimateSession({capacity:numeric('capacity'),from:numeric('from'),target:numeric('target'),averageKW:numeric('averageKW'),idleRate:fields.idleRate.trim()===''?null:numeric('idleRate'),graceMinutes:fields.graceMinutes.trim()===''?null:numeric('graceMinutes')},station,enteredRate,timestamp);
  if(!estimate){setError('Enter valid battery capacity, a higher target and expected average power. Estimates longer than 48 hours are unsupported. Check optional idle fields.');return;}
  setError('');setNow(timestamp);setActive({estimate,stationName:station.name,stationId:station.id,vehicleName,finishedAt:null});
 }
 const fieldLabels={capacity:'Usable battery capacity (kWh)',from:'Battery at start (%)',target:'Target battery (%)',averageKW:'Expected average charging power (kW)',idleRate:'Known idle fee ($/min), optional',graceMinutes:'Known idle grace period (min), optional'};
 return <section className="session-assistant" aria-label="Charge Session Assistant"><details open={!!active}><summary>Charge Session Assistant{active?` · ${active.stationName}`:''}</summary><p>Manual tracking only. Use the charger or operator app to start or stop charging. Keep this page open: reloading ends tracking, and reminders are in-page only.</p>
 {!active?<form onSubmit={e=>{e.preventDefault();start();}}><p>Selected: <strong>{station?.name}</strong> · {vehicleName}</p><div className="session-fields">{Object.entries(fieldLabels).map(([key,label])=><label key={key}>{label}<input type="number" step={key==='graceMinutes'?'1':'any'} min={key==='capacity'?10:key==='averageKW'?.1:0} max={key==='capacity'?250:key==='averageKW'?500:key==='graceMinutes'?180:100} value={fields[key as keyof typeof fields]} placeholder="Unknown" onChange={e=>{setFields(f=>({...f,[key]:e.target.value}));setStarted(false);}}/></label>)}</div><p className="muted-small">Use expected average power across this charge, not the station’s advertised maximum. No battery capacity is inferred from range. Unknown prices and idle fees remain unavailable.</p><label className="session-confirm"><input type="checkbox" checked={started} onChange={e=>setStarted(e.target.checked)}/>Charging has started at this selected station, and these are my entered estimates.</label>{error&&<p className="error-text" role="alert">{error}</p>}<Button type="submit" disabled={!started}>Start manual tracking</Button></form>:<>
 <p><strong>{active.stationName}</strong> · {active.vehicleName}. This session stays attached to this charger when you browse other stations.</p><div className="session-metrics"><span>Battery target<strong>{active.estimate.input.from}% → {active.estimate.input.target}%</strong></span><span>Planned energy<strong>~{active.estimate.energyKwh.toFixed(1)} kWh</strong></span><span>Estimated finish<strong>{new Date(active.estimate.finishAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} · {new Date(active.estimate.finishAt).toLocaleDateString()}</strong></span><span>At-start energy budget<strong>{active.estimate.energyCost===null?'Unavailable':`~$${active.estimate.energyCost.toFixed(2)} · ${active.estimate.price.label}`}</strong></span></div>
 <p className="muted-small">Rate source: {active.estimate.price.source}. Energy cost excludes taxes, charging losses, parking, session fees and idle fees. This is an estimate, not a measured battery level or an operator bill.</p>
 {clock&&active.finishedAt===null&&<p>{Math.ceil(clock.elapsedMs/60000)} minutes elapsed · {Math.ceil(clock.remainingMs/60000)} estimated minutes remaining.</p>}
 {clock?.checkTarget&&<p className="session-alert" role="status">Estimated target time reached. Check the vehicle now. Charging may still be running.</p>}
 {active.finishedAt!==null&&<><p>You marked charging finished at {new Date(active.finishedAt).toLocaleTimeString()}. This timestamp starts only your manual idle reminder.</p>{clock?.idleStartsAt===null?<p>Idle-fee timing is unknown. Check the operator’s grace period.</p>:clock&&<p>Entered grace period ends: {new Date(clock.idleStartsAt!).toLocaleTimeString()}.</p>}{clock?.idleDue&&<p className="session-alert" role="status">Your entered idle grace period has ended. Check the charger and move when appropriate.</p>}<p>Idle allowance from your manual finish time: {clock?.idleCost===null||!clock?'Unavailable':`~$${clock.idleCost.toFixed(2)}`}.</p><p className="muted-small">Actual idle-fee activation and billing increments depend on the operator. This reminder does not confirm a fee is being charged.</p></>}
 <div className="session-actions">{active.finishedAt===null&&<Button type="button" onClick={()=>{const timestamp=Date.now();setNow(timestamp);setActive(a=>a?{...a,finishedAt:timestamp}:null);}}>Mark charging finished</Button>}<Button type="button" variant="outline" onClick={()=>setActive(null)}>End tracking</Button></div>
 </>}
 </details></section>;
}
