import type { Profile } from './ev';

export type VehicleType = 'Sedan' | 'SUV' | 'Truck' | 'Hatchback' | 'Van';
export type CatalogVehicle = Profile & { make: string; model: string; type: VehicleType };

// Major battery-electric models sold or announced for the US market. Range and
// native connector are starting estimates because trim and model year matter.
export const vehicleCatalog = ([
  {make:'Acura',model:'ZDX',type:'SUV',name:'Acura ZDX',connector:'CCS1',range:313},
  {make:'Audi',model:'Q4 e-tron',type:'SUV',name:'Audi Q4 e-tron',connector:'CCS1',range:288},
  {make:'Audi',model:'Q6 e-tron',type:'SUV',name:'Audi Q6 e-tron',connector:'CCS1',range:321},
  {make:'Audi',model:'e-tron GT',type:'Sedan',name:'Audi e-tron GT',connector:'CCS1',range:300},
  {make:'BMW',model:'i4',type:'Sedan',name:'BMW i4',connector:'CCS1',range:318},
  {make:'BMW',model:'i5',type:'Sedan',name:'BMW i5',connector:'CCS1',range:295},
  {make:'BMW',model:'i7',type:'Sedan',name:'BMW i7',connector:'CCS1',range:314},
  {make:'BMW',model:'iX',type:'SUV',name:'BMW iX',connector:'CCS1',range:340},
  {make:'Cadillac',model:'Escalade IQ',type:'SUV',name:'Cadillac Escalade IQ',connector:'CCS1',range:450},
  {make:'Cadillac',model:'Lyriq',type:'SUV',name:'Cadillac Lyriq',connector:'CCS1',range:326},
  {make:'Cadillac',model:'Optiq',type:'SUV',name:'Cadillac Optiq',connector:'CCS1',range:300},
  {make:'Cadillac',model:'Vistiq',type:'SUV',name:'Cadillac Vistiq',connector:'CCS1',range:305},
  {make:'Chevrolet',model:'Blazer EV',type:'SUV',name:'Chevrolet Blazer EV',connector:'CCS1',range:334},
  {make:'Chevrolet',model:'Equinox EV',type:'SUV',name:'Chevrolet Equinox EV',connector:'CCS1',range:319},
  {make:'Chevrolet',model:'Silverado EV',type:'Truck',name:'Chevrolet Silverado EV',connector:'CCS1',range:460},
  {make:'Dodge',model:'Charger Daytona',type:'Hatchback',name:'Dodge Charger Daytona',connector:'CCS1',range:308},
  {make:'Fiat',model:'500e',type:'Hatchback',name:'Fiat 500e',connector:'CCS1',range:149},
  {make:'Ford',model:'F-150 Lightning',type:'Truck',name:'Ford F-150 Lightning',connector:'NACS',range:320},
  {make:'Ford',model:'Mustang Mach-E',type:'SUV',name:'Ford Mustang Mach-E',connector:'NACS',range:320},
  {make:'Genesis',model:'Electrified G80',type:'Sedan',name:'Genesis Electrified G80',connector:'CCS1',range:282},
  {make:'Genesis',model:'Electrified GV70',type:'SUV',name:'Genesis Electrified GV70',connector:'CCS1',range:236},
  {make:'Genesis',model:'GV60',type:'SUV',name:'Genesis GV60',connector:'CCS1',range:294},
  {make:'GMC',model:'Hummer EV Pickup',type:'Truck',name:'GMC Hummer EV Pickup',connector:'CCS1',range:381},
  {make:'GMC',model:'Hummer EV SUV',type:'SUV',name:'GMC Hummer EV SUV',connector:'CCS1',range:315},
  {make:'GMC',model:'Sierra EV',type:'Truck',name:'GMC Sierra EV',connector:'CCS1',range:460},
  {make:'Honda',model:'Prologue',type:'SUV',name:'Honda Prologue',connector:'CCS1',range:308},
  {make:'Hyundai',model:'IONIQ 5',type:'SUV',name:'Hyundai IONIQ 5',connector:'NACS',range:318},
  {make:'Hyundai',model:'IONIQ 6',type:'Sedan',name:'Hyundai IONIQ 6',connector:'NACS',range:342},
  {make:'Hyundai',model:'IONIQ 9',type:'SUV',name:'Hyundai IONIQ 9',connector:'NACS',range:335},
  {make:'Hyundai',model:'Kona Electric',type:'SUV',name:'Hyundai Kona Electric',connector:'CCS1',range:261},
  {make:'Jeep',model:'Wagoneer S',type:'SUV',name:'Jeep Wagoneer S',connector:'CCS1',range:294},
  {make:'Kia',model:'EV6',type:'SUV',name:'Kia EV6',connector:'NACS',range:319},
  {make:'Kia',model:'EV9',type:'SUV',name:'Kia EV9',connector:'NACS',range:304},
  {make:'Kia',model:'Niro EV',type:'SUV',name:'Kia Niro EV',connector:'CCS1',range:253},
  {make:'Lexus',model:'RZ',type:'SUV',name:'Lexus RZ',connector:'NACS',range:266},
  {make:'Lucid',model:'Air',type:'Sedan',name:'Lucid Air',connector:'NACS',range:512},
  {make:'Lucid',model:'Gravity',type:'SUV',name:'Lucid Gravity',connector:'NACS',range:450},
  {make:'Mercedes-Benz',model:'EQB',type:'SUV',name:'Mercedes-Benz EQB',connector:'CCS1',range:251},
  {make:'Mercedes-Benz',model:'EQE Sedan',type:'Sedan',name:'Mercedes-Benz EQE Sedan',connector:'CCS1',range:298},
  {make:'Mercedes-Benz',model:'EQE SUV',type:'SUV',name:'Mercedes-Benz EQE SUV',connector:'CCS1',range:302},
  {make:'Mercedes-Benz',model:'EQS Sedan',type:'Sedan',name:'Mercedes-Benz EQS Sedan',connector:'CCS1',range:390},
  {make:'Mercedes-Benz',model:'EQS SUV',type:'SUV',name:'Mercedes-Benz EQS SUV',connector:'CCS1',range:339},
  {make:'MINI',model:'Cooper Electric',type:'Hatchback',name:'MINI Cooper Electric',connector:'CCS1',range:218},
  {make:'MINI',model:'Countryman Electric',type:'SUV',name:'MINI Countryman Electric',connector:'CCS1',range:212},
  {make:'Nissan',model:'Ariya',type:'SUV',name:'Nissan Ariya',connector:'CCS1',range:304},
  {make:'Nissan',model:'Leaf',type:'Hatchback',name:'Nissan Leaf',connector:'CHAdeMO',range:212},
  {make:'Polestar',model:'2',type:'Hatchback',name:'Polestar 2',connector:'CCS1',range:320},
  {make:'Polestar',model:'3',type:'SUV',name:'Polestar 3',connector:'CCS1',range:350},
  {make:'Polestar',model:'4',type:'SUV',name:'Polestar 4',connector:'CCS1',range:310},
  {make:'Porsche',model:'Macan Electric',type:'SUV',name:'Porsche Macan Electric',connector:'CCS1',range:315},
  {make:'Porsche',model:'Taycan',type:'Sedan',name:'Porsche Taycan',connector:'CCS1',range:318},
  {make:'Rivian',model:'R1S',type:'SUV',name:'Rivian R1S',connector:'NACS',range:410},
  {make:'Rivian',model:'R1T',type:'Truck',name:'Rivian R1T',connector:'NACS',range:420},
  {make:'Subaru',model:'Solterra',type:'SUV',name:'Subaru Solterra',connector:'NACS',range:288},
  {make:'Tesla',model:'Cybertruck',type:'Truck',name:'Tesla Cybertruck',connector:'NACS',range:325},
  {make:'Tesla',model:'Model 3',type:'Sedan',name:'Tesla Model 3',connector:'NACS',range:363},
  {make:'Tesla',model:'Model S',type:'Sedan',name:'Tesla Model S',connector:'NACS',range:410},
  {make:'Tesla',model:'Model X',type:'SUV',name:'Tesla Model X',connector:'NACS',range:352},
  {make:'Tesla',model:'Model Y',type:'SUV',name:'Tesla Model Y',connector:'NACS',range:337},
  {make:'Toyota',model:'bZ',type:'SUV',name:'Toyota bZ',connector:'NACS',range:314},
  {make:'VinFast',model:'VF 8',type:'SUV',name:'VinFast VF 8',connector:'CCS1',range:264},
  {make:'VinFast',model:'VF 9',type:'SUV',name:'VinFast VF 9',connector:'CCS1',range:330},
  {make:'Volkswagen',model:'ID.4',type:'SUV',name:'Volkswagen ID.4',connector:'CCS1',range:291},
  {make:'Volkswagen',model:'ID. Buzz',type:'Van',name:'Volkswagen ID. Buzz',connector:'CCS1',range:234},
  {make:'Volvo',model:'EC40',type:'SUV',name:'Volvo EC40',connector:'NACS',range:297},
  {make:'Volvo',model:'EX30',type:'SUV',name:'Volvo EX30',connector:'NACS',range:261},
  {make:'Volvo',model:'EX40',type:'SUV',name:'Volvo EX40',connector:'NACS',range:296},
  {make:'Volvo',model:'EX90',type:'SUV',name:'Volvo EX90',connector:'NACS',range:310},
] satisfies CatalogVehicle[]).sort((a,b)=>a.make.localeCompare(b.make)||a.model.localeCompare(b.model));

export const vehicleTypes: VehicleType[] = ['SUV','Sedan','Truck','Hatchback','Van'];
export const vehicleMakes = [...new Set(vehicleCatalog.map(v=>v.make))];
